.TH UPFRONT 1
.SH NAME
upfront \- command line utility for the upfront npm package.
.SH SYNOPSIS
.B corrupt
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B upfront
command line utility that interacts with your project, automating various development tasks.
.SH OPTIONS
.TP
.BR make:[\fIoption\fR]
Generate the requested resource.
